# Generated by Django 2.0.5 on 2018-05-05 09:28

import django.contrib.postgres.fields.jsonb
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('banner', models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location=''), upload_to='')),
                ('audienceT_type', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('max_audience', models.IntegerField(default=0)),
                ('venue', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('venue_coordinate', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('region', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('currency', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('registration_fee', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('eventbasic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.EventBasic')),
                ('open_for_all', models.BooleanField(default=False)),
                ('screening_process', models.URLField(max_length=100)),
                ('registration_process', models.TextField(default='')),
                ('payment_process', models.URLField(max_length=150)),
                ('additional_fees', models.FloatField(null=True)),
                ('review_event_host', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            bases=('events.eventbasic',),
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('eventbasic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.EventBasic')),
                ('status_participant', models.BooleanField(default=True)),
                ('is_selection_pass', models.BooleanField(default=False)),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('registrationC_complete', models.BooleanField(default=False)),
                ('review_participant', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('rating_participant', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('confirmation_text', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participant', related_query_name='participant', to='userprofile.UserProfileBasic')),
            ],
            bases=('events.eventbasic',),
        ),
        migrations.CreateModel(
            name='EventTrainer',
            fields=[
                ('eventbasic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.EventBasic')),
                ('rating', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('status', models.BooleanField(default=False)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_trainer', related_query_name='trainer', to='userprofile.UserProfileBasic')),
            ],
            bases=('events.eventbasic',),
        ),
    ]
