# Generated by Django 2.0.5 on 2018-05-11 05:08

import django.contrib.postgres.fields.jsonb
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbasic',
            name='audienceT_type',
        ),
        migrations.AddField(
            model_name='eventbasic',
            name='audience_type',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='eventbasic',
            name='banner',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=''), upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventbasic',
            name='currency',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='eventbasic',
            name='region',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='eventbasic',
            name='registration_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventbasic',
            name='venue',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='eventbasic',
            name='venue_coordinate',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='additional_fees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='payment_process',
            field=models.URLField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='registration_process',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='review_event_host',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='screening_process',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
