# Generated by Django 2.0.5 on 2018-05-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='eventtrainer',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='eventtrainer',
            name='rating',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
