# Generated by Django 2.0.5 on 2018-05-08 20:11

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='eventparticipant',
            managers=[
                ('participant', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='registrationC_complete',
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='status_participant',
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='participant_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='registration_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventtrainer',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
