# Generated by Django 2.0.5 on 2018-05-13 17:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180508_2011'),
    ]
