# Generated by Django 2.0.5 on 2018-05-11 06:52

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180508_2011'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='eventtrainer',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
