# Generated by Django 2.0.5 on 2018-05-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180513_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
