# Generated by Django 2.0.5 on 2018-05-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='address',
            new_name='description',
        ),
    ]
