# Generated by Django 2.0.4 on 2018-05-05 00:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='test',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
