# Generated by Django 2.0.5 on 2018-05-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180504_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_student',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
