# Generated by Django 2.0.5 on 2018-05-11 21:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180511_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='payment_process',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='registration_process',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='review_event_host',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='screening_process',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='confirmation_text',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='rating_participant',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='review_participant',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
