# Generated by Django 2.0.5 on 2018-05-15 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_auto_20180514_2047'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='eventparticipant',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
