# Generated by Django 2.0.5 on 2018-05-12 06:42

import django.contrib.postgres.fields.jsonb
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_auto_20180512_0642'),
        ('events', '0004_auto_20180511_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetail',
            name='eventbasic_ptr',
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='eventbasic_ptr',
        ),
        migrations.RemoveField(
            model_name='eventtrainer',
            name='eventbasic_ptr',
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='audience_type',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='banner',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=''), upload_to=''),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='currency',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='max_audience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='region',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='registration_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='venue',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='venue_coordinate',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='audience_type',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='banner',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=''), upload_to=''),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='currency',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='max_audience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='region',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='registration_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='venue',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='venue_coordinate',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventtrainer',
            name='audience_type',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventtrainer',
            name='banner',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=''), upload_to=''),
        ),
        migrations.AddField(
            model_name='eventtrainer',
            name='currency',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventtrainer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventtrainer',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventtrainer',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtrainer',
            name='max_audience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='eventtrainer',
            name='region',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventtrainer',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventtrainer',
            name='registration_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventtrainer',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventtrainer',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventtrainer',
            name='venue',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='eventtrainer',
            name='venue_coordinate',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EventBasic',
        ),
    ]
