# Generated by Django 2.0.5 on 2018-05-15 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180515_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdetail',
            old_name='user',
            new_name='owner',
        ),
    ]
