# Generated by Django 2.0.5 on 2018-05-05 06:51

import django.contrib.postgres.fields.jsonb
import django.core.files.storage
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_total_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('uiqueid_event', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('banner', models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location=''), upload_to='')),
                ('audienceT_type', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('max_audience', models.IntegerField(default=0)),
                ('venue', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('venue_coordinate', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('region', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('cuurency', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('registration_fee', models.FloatField(null=True)),
                ('open_for_all', models.BooleanField(default=False)),
                ('screening_process', models.URLField(max_length=100)),
                ('registration_process', models.TextField(default='')),
                ('payment_process', models.URLField(max_length=150)),
                ('additional_fees', models.FloatField(null=True)),
                ('review_event_host', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('uiqueid_event', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('banner', models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location=''), upload_to='')),
                ('audienceT_type', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('max_audience', models.IntegerField(default=0)),
                ('venue', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('venue_coordinate', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('region', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('cuurency', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('registration_fee', models.FloatField(null=True)),
                ('status_participant', models.BooleanField(default=True)),
                ('is_selection_pass', models.BooleanField(default=False)),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('registrationC_complete', models.BooleanField(default=False)),
                ('review_participant', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('rating_participant', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('confirmation_text', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventTrainer',
            fields=[
                ('uiqueid_event', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('banner', models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location=''), upload_to='')),
                ('audienceT_type', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('max_audience', models.IntegerField(default=0)),
                ('venue', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('venue_coordinate', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('region', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('cuurency', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('registration_fee', models.FloatField(null=True)),
                ('rating', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
