# Generated by Django 2.0.5 on 2018-05-15 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180515_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
