# Generated by Django 2.0.5 on 2018-05-19 08:40

import django.contrib.postgres.fields.jsonb
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20180515_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='banner',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='media/event_img/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='confirmation_text',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='rating_participant',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='review_participant',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
