# Generated by Django 2.0.5 on 2018-05-11 06:52

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicantManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelManagers(
            name='jobpostbasic',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
