# Generated by Django 2.0.5 on 2018-05-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='jobapplicant',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='apply_status',
            field=models.BooleanField(default=False),
        ),
    ]
