# Generated by Django 2.0.5 on 2018-05-12 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostbasic',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobpostdetails',
            name='job_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobpost.JobPostBasic'),
        ),
    ]
