# Generated by Django 2.0.5 on 2018-05-18 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0002_auto_20180513_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplicant',
            old_name='applicant_id',
            new_name='applicant',
        ),
        migrations.RenameField(
            model_name='jobapplicant',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='jobpostbasic',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='jobpostdetails',
            old_name='job_id',
            new_name='job',
        ),
    ]
