# Generated by Django 2.0.5 on 2018-05-13 16:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0002_auto_20180512_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostbasic',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
