# Generated by Django 2.0.5 on 2018-05-12 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0002_auto_20180511_0652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpostbasic',
            old_name='organization_id',
            new_name='organizationprofile',
        ),
        migrations.RenameField(
            model_name='jobpostdetails',
            old_name='job_id',
            new_name='jobpostbasic',
        ),
    ]
