# Generated by Django 2.0.5 on 2018-05-12 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0002_jobapplicantmanager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpostbasic',
            options={'permissions': (('view_post', 'Can see job post'),)},
        ),
    ]
