# Generated by Django 2.0.5 on 2018-05-18 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0002_auto_20180513_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicant',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobpost.JobPostBasic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpostbasic',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobpostdetails',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobpost.JobPostBasic'),
        ),
    ]
