# Generated by Django 2.0.5 on 2018-05-18 09:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0003_auto_20180518_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostbasic',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
