# Generated by Django 2.0.5 on 2018-05-19 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0004_jobpostbasic_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicant',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
