# Generated by Django 2.0.5 on 2018-05-05 05:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationprofile',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='date_joined',
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
