# Generated by Django 2.0.5 on 2018-05-12 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20180511_0736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalprofile',
            options={'permissions': (('create_profile', 'can create profile'), ('update_profile', 'can update profile'))},
        ),
        migrations.AddField(
            model_name='userprofilebasic',
            name='is_organization',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofilebasic',
            name='auth',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
