# Generated by Django 2.0.5 on 2018-05-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20180505_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True),
        ),
    ]
