# Generated by Django 2.0.5 on 2018-05-05 03:52

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('address', models.TextField()),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('gravatar', models.CharField(blank=True, max_length=200, null=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=100)),
                ('is_training_institute', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('industry_type', models.CharField(max_length=50)),
                ('website', models.URLField(blank=True, max_length=100, null=True)),
                ('founded_on', models.DateField()),
                ('company_size', models.CharField(max_length=100)),
                ('additional_contact', models.CharField(blank=True, max_length=13, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('address', models.TextField()),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('gravatar', models.CharField(blank=True, max_length=200, null=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('is_trainer', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('education', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('experience', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('experience_years', models.IntegerField(default=0, help_text='experience in months')),
                ('current_organization', models.TextField(blank=True, null=True)),
                ('official_contact', models.CharField(max_length=13)),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('user', django.db.models.manager.Manager()),
            ],
        ),
    ]
